---
- hosts: 127.0.0.1
  tasks:
  - include: tasks/basics.yml
  #- include: tasks/git.yml
  # languages
  - include: tasks/lang/java.yml
  - include: tasks/lang/python.yml
  # desktop apps
  - include: tasks/apps/atom.yml
