---
- hosts: 127.0.0.1
  become: true
  vars:
    atom_upgrade_all: True
    atom_packages:
    - ariake-dark-syntax
    - atom-material-syntax
    - atom-material-ui
    - busy-signal
    - editorconfig
    - emmet
    - file-icons
    - fonts
    - git-plus
    - intentions
    - language-ansible
    - language-docker
    - language-groovy
    - language-powershell
    - linter
    - linter-eslint
    - linter-pylama
    - nord-atom-syntax
    - nord-atom-ui
    - pretty-json
    - seti-ui
    - terminal-plus
    - vim-mode-plus
  vars_files:
  - vars/general.yml
  handlers:
  - name: apt cache update
    apt: update_cache=true
  tasks:
  # basics
  # - include: tasks/basics.yml
  # - include: tasks/theme.yml
  # - include: tasks/zsh.yml
  # - include: tasks/git.yml

  # languages
  # - include: tasks/lang/go.yml
  # - include: tasks/lang/java.yml
  # - include: tasks/lang/javascript.yml
  # - include: tasks/lang/python.yml
  # - include: tasks/lang/ruby.yml

  # tools
  # - include: tasks/tools/awscli.yml
  # - include: tasks/tools/azurecli.yml
  #- include: tasks/tools/docker.yml
  # - include: tasks/tools/gcloud.yml
  # - include: tasks/tools/packer.yml
  # - include: tasks/tools/terraform.yml

  # docker
  - include: tasks/tools/docker-clean.yml
  - include: tasks/tools/whalebrew.yml

  # desktop apps
  #- include: tasks/apps/atom.yml

  roles:
  - { role: angstwad.docker_ubuntu }
  - { role: jgkim.atom, become_user: "{{ansible_user_id}}" }
