---
- name: install basic softwares
  become: true
  apt: name="{{item}}"
  with_items:
  - automake
  - build-essential
  - curl
  - git
  - git-core
  - python-software-properties
  - unzip
  - wget
  - zip
  - zlib1g-dev

# TODO: create ~/Code folder
# TODO: clone github projects into Code folder
