---
- name: install basic softwares
  become: true
  apt: name="{{item}}"
  with_items: "{{basic_system_packages}}"

- name: install shells
  become: true
  apt: name="{{item}}"
  with_items: "{{shells}}"

- name: add docker group
  become: true
  group: name=docker

- name: setup user
  become: true
  user:
    name: "{{ansible_user_id}}"
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: create code folder
  file:
    path: "/home/{{ansible_user_id}}/Code"
    state: directory
    mode: 0755

# TODO: clone github projects into Code folder
