---
- name: install basic softwares
  become: true
  apt: name="{{item}}"
  with_items:
  - automake
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - git
  - git-core
  - python-software-properties
  - software-properties-common
  - unzip
  - wget
  - zip
  - zlib1g-dev

- name: install shells
  become: true
  apt: name="{{item}}"
  with_items:
  - terminator
  - zsh

- name: setup user
  become: true
  user:
    name: "{{ansible_user_id}}"
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: add docker group
  become: true
  group: name=docker

- name: create code folder
  file:
    path: "/home/{{ansible_user_id}}/Code"
    state: directory
    mode: 0755

# TODO: clone github projects into Code folder
