---
- name: set git email
  git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"

- name: set git name
  git_config:
    name: user.name
    scope: global
    value: "{{git_name}}"

- name: set git push
  git_config:
    name: push.default
    scope: global
    value: simple
