---
- name: install java
  become: true
  apt: name="{{ item }}"
  with_items:
  - default-jre
  - default-jdk
  - maven

- name: download sdkman
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman.sh
    mode: 0775

# TODO: skip if installed
- name: install sdkman
  command: /tmp/sdkman.sh

# TODO: skip if installed
- name: install sdkman packages
  shell: 'source ~/.sdkman/bin/sdkman-init.sh && sdk install {{item}}'
  with_items: "{{java_sdkman_packages}}"
  args:
    executable: /bin/bash
