---
# TODO: dont run if already installed
- name: install node ppa
  shell: 'curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -'
  args:
    executable: /bin/bash
  notify:
  - apt cache update

- name: install nodejs
  apt: name=nodejs

- name: install global npm packages
  npm: name="{{item}}" global=yes
  with_items: "{{npm_packages}}"
