---
- name: install python
  become: true
  apt: name="{{item}}"
  with_items:
  - build-essential
  - libffi-dev
  - libssl-dev
  - python
  - python-dev
  - python-pip
  - python3
  - python3-dev
  - python3-pip

- name: install pip3 packages
  become: true
  pip: name="{{item}}" state=latest executable=/usr/bin/pip3
  with_items: "{{pip_packages}}"

- name: upgrade pip
  become: true
  pip: name=pip state=latest

- name: install pip packages
  become: true
  pip: name="{{item}}" state=latest
  with_items: "{{pip_packages}}"
