---
- name: add azurecli repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/azure-cli/ wheezy main"
    state: present

- name: add azurecli key repo
  apt_key: keyserver="apt-mo.trafficmanager.net" id=417A0893
  notify:
  - apt cache update

- name: install dependencies
  apt: name=apt-transport-https

- name: install azurecli
  apt: name=azure-cli
