---
- shell: uname -r
  ignore_errors: yes
  register: uname_result

- name: install linux-image packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - linux-image-extra-{{ uname_result.stdout }}
    - linux-image-extra-virtual

# TODO: create variables for key server
- name: add docker repo gpg keys
  become: true
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D

# TODO: alter this to find release from ansible facts
- name: add docker repository
  become: true
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present

- name: update cache
  become: true
  apt:
    update_cache: true

- name: install docker
  become: true
  apt: name="docker-engine"

- name: add docker group
  become: true
  group: name=docker

- name: add current user to docker group
  become: true
  user:
    name: "{{ansible_user_id}}"
    groups: docker

# TODO: make this a handler
- name: restart docker
  become: true
  service: name=docker state=restarted
