---
# TODO: create update and sha checks for multiple version
- name: get terraform
  get_url:
    url: "{{packer_url}}"
    dest: /tmp/packer.zip
    checksum: "{{packer_checksum}}"

- name: unzip terraform
  become: true
  unarchive:
    src: /tmp/packer.zip
    dest: /usr/local/bin/
    creates: /usr/local/bin/packer
