---

# TODO: create update and sha checks for multiple version
- name: get terraform
  get_url:
    url: "{{terraform_url}}"
    dest: /tmp/terraform.zip
    checksum: "{{terraform_checksum}}"

- name: unzip terraform
  become: true
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    creates: /usr/local/bin/terraform
