---

# TODO: create update and sha checks for multiple version
- name: get terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.9.2/terraform_0.9.2_linux_amd64.zip?_ga=1.241782721.2107522903.1487362906
    dest: /tmp/terraform.zip
    checksum: sha256:a916228ea4c19c91c9a5dee2905885f517eb7c31ba4dbf5d79f9f36606973313

- name: unzip terraform
  become: true
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    creates: /usr/local/bin/terraform
